// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminBugReport = { id: bigint, unid: string, bugtype: string, similarityhash: number, message: string | null, exceptionmessage: string | null, stacktrace: string | null, userlogin: string | null, url: string | null, useragent: string | null, application: string | null, created: string, total_count: bigint, similar_count: bigint, };
