// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminBugType = "Bug" | "Server" | "Wasm" | "LeptosWarning" | "BrowserWarning" | "Database" | "ExternalApi" | "TimezoneDetection" | "JsError" | "PromiseRejection" | "ExtensionError" | "CareerApiError";
