// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AvailabilityRuleInput = { weekday: number, start_time: string, end_time: string, slot_minutes: number, };
