// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookingResult = { event_id: string, meet_link: string | null, html_link: string | null, };
