// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Booking = { unid: string, host_unid: string, lead_unid: string | null, slot_start: string, timezone: string, invitee_name: string, invitee_email: string, status: string, google_meet_url: string | null, created_at: string, };
