// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventDateTime } from "./EventDateTime";

export type CalendarEvent = { id: string, summary: string | null, description: string | null, start: EventDateTime | null, end: EventDateTime | null, htmlLink: string | null, };
