// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CallingVisitEngagement = { unid: string, duration_seconds: number | null, form_started: boolean | null, form_submitted: boolean | null, booked_call: boolean | null, };
