// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CallingVisitRequest = { source_page: string | null, referer: string | null, utm_source: string | null, utm_medium: string | null, utm_campaign: string | null, user_agent: string | null, };
