// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateBookingRequest = { lead_unid: string | null, calling_visit_unid: string | null, slot_start: string, timezone: string, invitee_name: string, invitee_email: string, };
