// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LeadUpdate = { first_name: string | null, last_name: string | null, email: string | null, phone: string | null, country_code: string | null, investment_comfort: string | null, what_stopping_you: string | null, source_page: string | null, utm_source: string | null, utm_medium: string | null, utm_campaign: string | null, qualification_status: string | null, };
