// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type SessionUser = { unid: string, email: string, full_name: string, roles: Array<Role>, };
