/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as BookACallRouteImport } from './routes/book-a-call'
import { Route as BookingConfirmationRouteImport } from './routes/booking-confirmation'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminBugReportsRouteImport } from './routes/admin/bug-reports'
import { Route as AdminCallingVisitsRouteImport } from './routes/admin/calling-visits'
import { Route as AdminGoogleOauthCallbackRouteImport } from './routes/admin/google-oauth-callback'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminRoleaccessesRouteImport } from './routes/admin/roleaccesses'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAvailabilityRouteImport } from './routes/dashboard/availability'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as DashboardCalendarCallbackRouteImport } from './routes/dashboard/calendar/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookACallRoute = BookACallRouteImport.update({
  id: '/book-a-call',
  path: '/book-a-call',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking-confirmation',
  path: '/booking-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBugReportsRoute = AdminBugReportsRouteImport.update({
  id: '/bug-reports',
  path: '/bug-reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCallingVisitsRoute = AdminCallingVisitsRouteImport.update({
  id: '/calling-visits',
  path: '/calling-visits',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGoogleOauthCallbackRoute =
  AdminGoogleOauthCallbackRouteImport.update({
    id: '/google-oauth-callback',
    path: '/google-oauth-callback',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoleaccessesRoute = AdminRoleaccessesRouteImport.update({
  id: '/roleaccesses',
  path: '/roleaccesses',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAvailabilityRoute = DashboardAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCalendarCallbackRoute =
  DashboardCalendarCallbackRouteImport.update({
    id: '/calendar/callback',
    path: '/calendar/callback',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/book-a-call': typeof BookACallRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/bug-reports': typeof AdminBugReportsRoute
  '/admin/calling-visits': typeof AdminCallingVisitsRoute
  '/admin/google-oauth-callback': typeof AdminGoogleOauthCallbackRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/roleaccesses': typeof AdminRoleaccessesRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/calendar/callback': typeof DashboardCalendarCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-a-call': typeof BookACallRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/bug-reports': typeof AdminBugReportsRoute
  '/admin/calling-visits': typeof AdminCallingVisitsRoute
  '/admin/google-oauth-callback': typeof AdminGoogleOauthCallbackRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/roleaccesses': typeof AdminRoleaccessesRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/calendar/callback': typeof DashboardCalendarCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/book-a-call': typeof BookACallRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/bug-reports': typeof AdminBugReportsRoute
  '/admin/calling-visits': typeof AdminCallingVisitsRoute
  '/admin/google-oauth-callback': typeof AdminGoogleOauthCallbackRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/roleaccesses': typeof AdminRoleaccessesRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/calendar/callback': typeof DashboardCalendarCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/book-a-call'
    | '/booking-confirmation'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms'
    | '/admin/bookings'
    | '/admin/bug-reports'
    | '/admin/calling-visits'
    | '/admin/google-oauth-callback'
    | '/admin/leads'
    | '/admin/roleaccesses'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/calendar/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-a-call'
    | '/booking-confirmation'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms'
    | '/admin/bookings'
    | '/admin/bug-reports'
    | '/admin/calling-visits'
    | '/admin/google-oauth-callback'
    | '/admin/leads'
    | '/admin/roleaccesses'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/admin'
    | '/dashboard'
    | '/dashboard/calendar/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/book-a-call'
    | '/booking-confirmation'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms'
    | '/admin/bookings'
    | '/admin/bug-reports'
    | '/admin/calling-visits'
    | '/admin/google-oauth-callback'
    | '/admin/leads'
    | '/admin/roleaccesses'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/calendar/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  BookACallRoute: typeof BookACallRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-call': {
      id: '/book-a-call'
      path: '/book-a-call'
      fullPath: '/book-a-call'
      preLoaderRoute: typeof BookACallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmation': {
      id: '/booking-confirmation'
      path: '/booking-confirmation'
      fullPath: '/booking-confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bug-reports': {
      id: '/admin/bug-reports'
      path: '/bug-reports'
      fullPath: '/admin/bug-reports'
      preLoaderRoute: typeof AdminBugReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/calling-visits': {
      id: '/admin/calling-visits'
      path: '/calling-visits'
      fullPath: '/admin/calling-visits'
      preLoaderRoute: typeof AdminCallingVisitsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/google-oauth-callback': {
      id: '/admin/google-oauth-callback'
      path: '/google-oauth-callback'
      fullPath: '/admin/google-oauth-callback'
      preLoaderRoute: typeof AdminGoogleOauthCallbackRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roleaccesses': {
      id: '/admin/roleaccesses'
      path: '/roleaccesses'
      fullPath: '/admin/roleaccesses'
      preLoaderRoute: typeof AdminRoleaccessesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/availability': {
      id: '/dashboard/availability'
      path: '/availability'
      fullPath: '/dashboard/availability'
      preLoaderRoute: typeof DashboardAvailabilityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calendar/callback': {
      id: '/dashboard/calendar/callback'
      path: '/calendar/callback'
      fullPath: '/dashboard/calendar/callback'
      preLoaderRoute: typeof DashboardCalendarCallbackRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBugReportsRoute: typeof AdminBugReportsRoute
  AdminCallingVisitsRoute: typeof AdminCallingVisitsRoute
  AdminGoogleOauthCallbackRoute: typeof AdminGoogleOauthCallbackRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminRoleaccessesRoute: typeof AdminRoleaccessesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBugReportsRoute: AdminBugReportsRoute,
  AdminCallingVisitsRoute: AdminCallingVisitsRoute,
  AdminGoogleOauthCallbackRoute: AdminGoogleOauthCallbackRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminRoleaccessesRoute: AdminRoleaccessesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAvailabilityRoute: typeof DashboardAvailabilityRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCalendarCallbackRoute: typeof DashboardCalendarCallbackRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAvailabilityRoute: DashboardAvailabilityRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCalendarCallbackRoute: DashboardCalendarCallbackRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  BookACallRoute: BookACallRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
