/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminBugReportsRouteImport } from './routes/admin/bug-reports'
import { Route as AdminCallingVisitsRouteImport } from './routes/admin/calling-visits'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminRoleaccessesRouteImport } from './routes/admin/roleaccesses'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAvailabilityRouteImport } from './routes/dashboard/availability'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as DashboardBugsRouteImport } from './routes/dashboard/bugs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBugReportsRoute = AdminBugReportsRouteImport.update({
  id: '/bug-reports',
  path: '/bug-reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCallingVisitsRoute = AdminCallingVisitsRouteImport.update({
  id: '/calling-visits',
  path: '/calling-visits',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoleaccessesRoute = AdminRoleaccessesRouteImport.update({
  id: '/roleaccesses',
  path: '/roleaccesses',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAvailabilityRoute = DashboardAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBugsRoute = DashboardBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/bug-reports': typeof AdminBugReportsRoute
  '/admin/calling-visits': typeof AdminCallingVisitsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/roleaccesses': typeof AdminRoleaccessesRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/bugs': typeof DashboardBugsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/bug-reports': typeof AdminBugReportsRoute
  '/admin/calling-visits': typeof AdminCallingVisitsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/roleaccesses': typeof AdminRoleaccessesRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/bugs': typeof DashboardBugsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/bug-reports': typeof AdminBugReportsRoute
  '/admin/calling-visits': typeof AdminCallingVisitsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/roleaccesses': typeof AdminRoleaccessesRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/bugs': typeof DashboardBugsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/bug-reports'
    | '/admin/calling-visits'
    | '/admin/leads'
    | '/admin/roleaccesses'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/bugs'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/bug-reports'
    | '/admin/calling-visits'
    | '/admin/leads'
    | '/admin/roleaccesses'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/bugs'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/bug-reports'
    | '/admin/calling-visits'
    | '/admin/leads'
    | '/admin/roleaccesses'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/bugs'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bug-reports': {
      id: '/admin/bug-reports'
      path: '/bug-reports'
      fullPath: '/admin/bug-reports'
      preLoaderRoute: typeof AdminBugReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/calling-visits': {
      id: '/admin/calling-visits'
      path: '/calling-visits'
      fullPath: '/admin/calling-visits'
      preLoaderRoute: typeof AdminCallingVisitsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roleaccesses': {
      id: '/admin/roleaccesses'
      path: '/roleaccesses'
      fullPath: '/admin/roleaccesses'
      preLoaderRoute: typeof AdminRoleaccessesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/availability': {
      id: '/dashboard/availability'
      path: '/availability'
      fullPath: '/dashboard/availability'
      preLoaderRoute: typeof DashboardAvailabilityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bugs': {
      id: '/dashboard/bugs'
      path: '/bugs'
      fullPath: '/dashboard/bugs'
      preLoaderRoute: typeof DashboardBugsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBugReportsRoute: typeof AdminBugReportsRoute
  AdminCallingVisitsRoute: typeof AdminCallingVisitsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminRoleaccessesRoute: typeof AdminRoleaccessesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBugReportsRoute: AdminBugReportsRoute,
  AdminCallingVisitsRoute: AdminCallingVisitsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminRoleaccessesRoute: AdminRoleaccessesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAvailabilityRoute: typeof DashboardAvailabilityRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardBugsRoute: typeof DashboardBugsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAvailabilityRoute: DashboardAvailabilityRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardBugsRoute: DashboardBugsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
